version: "3.9"
services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=flowise
      - POSTGRES_PASSWORD=flowise
      - POSTGRES_DB=flowise
      - POSTGRES_HOST_AUTH_METHOD=md5
      - POSTGRES_INITDB_ARGS=--auth-host=md5
    volumes:
      - postgres-data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 500M
    ports:
      - "5432:5432"
  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
    environment:
      MINIO_ACCESS_KEY: minio_access_key
      MINIO_SECRET_KEY: minio_secret_key
    command: server /data --console-address ":9001"
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1G

  trino-coordinator:
    image: "trinodb/trino:431"
    ports:
      - '8080:8080'
    volumes:
      - ./trino/coordinator/etc:/etc/trino:ro
    depends_on:
      - trino-worker
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 3G

  trino-worker:
    image: "trinodb/trino:431"
    volumes:
      - ./trino/worker/etc:/etc/trino:ro
    deploy:
      mode: replicated
      replicas: 2
      resources:
        limits:
          cpus: "2"
          memory: 6G

  flowise:
    build: ./flowise
    ports:
      - "3000:3000"
    depends_on:
      - trino-coordinator
    environment:
      - DEBUG=true
      - DATABASE_TYPE=postgres
      - DATABASE_PORT=5432
      - DATABASE_HOST=postgres
      - DATABASE_NAME=flowise
      - DATABASE_USER=flowise
      - DATABASE_PASSWORD=flowise
      - LOG_LEVEL=debug
#      - LOG_PATH=${LOG_PATH}
    command: /bin/sh -c "sleep 3; flowise start --DEBUG=true"

#  autogen:
#    build: ./autogen

#  run build.sh in trino-ai-assistant directory first
  trino-ai-assistant:
    build: ./trino-ai-assistant
    environment:
      openai_api_key: your openai key
      openai_api_base_url: https://api.mctools.online/v1
#      if you need proxy to access openai
#      http_proxy: http://loclahost:10809
    depends_on:
      - trino-coordinator
#    ports:
#      - "9080:9080"
#      - "7080:7080"

volumes:
  minio-data:
    driver: local
  postgres-data:
    driver: local
